online_shop/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', add_to_cart, name='add_to_cart'),
    # path('decrease/<int:product_id>/', views.decrease_from_cart, name='decrease_from_cart'),
    path('detail/', cart_detail, name='cart_detail'),
    path('remove/<int:product_id>', remove, name='remove'),
    path('cart_remove/', cart_remove, name='cart_remove'),
    path('decrease_from_cart/<int:product_id>/', decrease_from_cart, name='decrease_from_cart'),
]

online_shop/online_shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
    path('account/', include('account.urls', namespace='account')),
    path('seller/', include('seller.urls', namespace='seller')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
]

online_shop/order/urls.py
from django.urls import path
from .views import *

app_name = 'order'

urlpatterns = [
    path('create/', order_creation, name='order_creation'),
    path('veryfi-code/', verify_code, name='verify_code'),
    path('veryfi-phone/', verify_phone, name='verify_phone'),
]

online_shop/shop/urls.py
app_name = 'shop'
from django.urls import path
from .views import *

urlpatterns = [
    path('products/', product_list, name='products_list'),
    path('products/category/<slug:category_slug>/', product_list, name='products_list_by_category'),
    path('product/<int:pk>/<slug:slug>/', product_detail, name='product_detail'),
]

online_shop/cart/models.py
from django.db import models

# Create your models here.

online_shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .cart import Cart
from shop.models import Product


# Create your views here.

def add_to_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product)
    return redirect(request.META.get('HTTP_REFERER', 'shop:product_list'))


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart_detail.html', {'cart': cart})


def remove(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart = Cart(request)
    cart.remove(product)
    return redirect(request.META.get('HTTP_REFERER', 'cart:cart_detail'))


def cart_remove(request):
    cart = Cart(request)
    cart.clear()
    return redirect(request.META.get('HTTP_REFERER', 'cart:cart_detail'))


def decrease_from_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.decrease(product)
    return redirect(request.META.get('HTTP_REFERER', 'cart:cart_detail'))

online_shop/cart/templates/cart_detail.html
{%for item in cart%}
<p>نام محصول:{{item.product.name}}</p>

<p>قیمت:{{item.product.price}}</p>
<p>قیمت پس از تخفیف:{{item.price}}</p>
<p>{{item.quantity}}:تعداد</p>
<p>{{item.product.weight}}:وزن محصول</p>
<p>قیمت کل:{{item.total}}</p>
<a href="{% url 'cart:add_to_cart' item.product.pk %}">+</a><br>
<a href="{% url 'cart:decrease_from_cart' item.product.pk %}">-</a><br>
<a href="{% url 'cart:remove' item.product.pk %}">حذف محصول از سبد خرید</a><br>
<hr>



{%endfor%}
<p>{{cart.get_total_price}}:مجموع قیمت</p>
<a href="{% url 'cart:cart_remove' %}">حذف سبد خرید</a><br>
<a href="{% url 'order:verify_phone' %}">ادامه پرداخت</a><br>
<a href="{% url 'shop:products_list' %}">بازگشت به لیست محصولات</a>